First, exploring the logic directly in this notebook, testing how to generate and structure the data.   
Next, the logic will be abstracted into a class (RandomGenerator) for clean reuse.

In [1]:
import random
import pandas as pd # type: ignore

columns = [{"name": f"N{i+1}", "min": 1, "max": 69} for i in range(5)] + [{"name": "B", "min": 1, "max": 26}]
n_rows = 10
max_columns = 100

if len(columns) > max_columns:
    raise ValueError("Too many columns.")

data = []
for _ in range(n_rows):
    row = [random.randint(col["min"], col["max"]) for col in columns]
    data.append(row)

df = pd.DataFrame(data, columns=[col["name"] for col in columns])
df.head()

   N1  N2  N3  N4  N5   B
0   3  20  61  23  41   1
1  54  30  51  59   3  13
2  26  39   7  44  55   9
3  43   7  11  69  69  17
4  53  30  28  34  69   7

RandomGenetator class is implemented in 
    ```./generator/random_generator.py```

Now, let's Import and test that class directly in the notebook:

In [2]:
import sys
sys.path.append("..")  # Add the parent directory to the path
from generator.random_generator import RandomGenerator

# columns = [{"name": f"N{i+1}", "min": 1, "max": 69} for i in range(5)] + [{"name": "B", "min": 1, "max": 26}]
# gen = RandomGenerator(n_rows=10, columns=columns)

gen = RandomGenerator(n_rows=10)  # No columns argument; uses the class default
df = gen.generate()
gen.to_csv()  # Saves the DataFrame to a file after generating it
df.head(11)

[INFO] CSV saved to: output\random_generated_20250511_164125.csv (1/10)

   N1  N2  N3  N4  N5   B
0   7  50  49  21  56  24
1  69  66   3   8  66  16
2  35  10  35  51  44  24
3  62  18   4  50  35  14
4  67  48  36  25  58  14
5  23  32  57  66  23  26
6  11  29  59   6  60  14
7   5  59  41  37  15  21
8  29  39   9  56  63  25
9  17  16  55  33  45  19

 TODO: Implement Constraints System 
 ----------------------------------- 
 - Add support for enforcing global and column-specific constraints during number generation. 
 - Example constraints: 
     * Sum of N1â€“N5 must be less than 150. 
     * N1 must be even if N2 > 10. 
     * All values must be unique per row. 
  
 - Design Plan: 
     * Implement a dedicated Constraints class to handle complex logic. 
     * Allow passing constraints as callable objects or functions to RandomGenerator. 
     * Constraints should support: 
        - Cross-column dependencies. 
        - Uniqueness checks. 
        - Aggregate conditions (sum, mean, etc.). 
        - Conditional logic between fields.

Update the constructor to accept a constraints parameter:

```python
    def __init__(self, n_rows, columns=None, max_columns=100, constraints=None):
        self.constraints = constraints
```

Example usage:

```python
    gen = RandomGenerator(n_rows=1000, columns=columns, constraints=MyConstraintClass())
```